### PR TITLE
Update burp-ext.py

### PR DESCRIPTION
**Pull request by falasi**
Added support for loading the introspection schema.json locally that was on your todo list #4Allow for importing a Schema file as an alternative option to Introspection. Thanks for this awesome script. It will try to fetch the schema via URL else read the schema.json locally

### CODE REVIEW

**Comment by jmeit-fwdsec** [comment]
This is wonderful! Thank you. Can you resubmit this without the README changes from your fork? I'll test your code this week and merge.

**Comment by falasi** [comment]
I will make one slight improvement and resubmit it again later this week. I wont include the README that was accidently submitted. I just want to add a function that imports the schema.json as it currently takes a string as the file path. Will work on it this week and resubmit it. Thank you for this awesome extension.

**Comment by falasi** [comment]
Hey, I managed to find time tonight and completed it. I checked this pull Request and now only see 1 file changes. Hope that I resubmitted this correctly. Thanks so much for this script I managed to find authorization issues on an engagement. your a legend. peace

**Comment by jmeit-fwdsec** [comment]
You are the absolute man! Thank you so much for doing this!
I'm genuinely so happy to know that this extension helped you find issues!

**Pull request merged**
